import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/globals.css";
import ProjectCard from "./project-card";
import Image from 'next/image';
import TecCard from "./tec-card";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-body">
        <nav className="z-20 fixed w-full top-0 left-0 bg-white border-gray-200 dark:bg-gray-900 p-5">
          <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
            <img src="/logo.png" alt="profile" className=" w-40 object-cover" />
            <div className="hidden w-full md:block md:w-auto" id="navbar-default">
              <ul className="font-medium flex flex-col p-4 md:p-0 mt-4 border  md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0">
                <li>
                  <a href="#" className="block py-2 px-3  rounded  md:border-0 text-gray-200 md:hover:text-custom-blue md:p-0">About me</a>
                </li>
                <li>
                  <a href="#" className="block py-2 px-3  rounded  md:border-0 text-gray-200 md:hover:text-custom-blue md:p-0">Projects</a>
                </li>
                <li>
                  <a href="#" className="block py-2 px-3  rounded  md:border-0 text-gray-200 md:hover:text-custom-blue md:p-0">Technologies</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        <div className="mt-28 container-start flex flex-wrap flex-col items-center justify-center p-10 w-full mb-5  h-screen">
          <img src="/profile.jpg" alt="profile" className=" md:w-96 object-cover rounded-t-lg h-96  md:w-96 md:rounded-full " />
          <div className="flex flex-wrap flex-col items-center">
            <h1 className="text-4xl p-3 "> Hi , I'm Pedro Santos </h1>
            <div className="text-animation mb-3 p-3">
              <div className="text-xl "> Software Engineer  </div>
              <div className="text-xl "> Full Stack Developer  </div>
              <div className="text-xl "> Game Developer  </div>

            </div>

            <div className="flex flex-row gap-3">

              <a href="#" className="custom-button py-2 px-4  rounded inline-flex gap-3  items-center">
                <svg className="w-8 " fill="#ffffff" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" >    <path d="M17.791,46.836C18.502,46.53,19,45.823,19,45v-5.4c0-0.197,0.016-0.402,0.041-0.61C19.027,38.994,19.014,38.997,19,39 c0,0-3,0-3.6,0c-1.5,0-2.8-0.6-3.4-1.8c-0.7-1.3-1-3.5-2.8-4.7C8.9,32.3,9.1,32,9.7,32c0.6,0.1,1.9,0.9,2.7,2c0.9,1.1,1.8,2,3.4,2 c2.487,0,3.82-0.125,4.622-0.555C21.356,34.056,22.649,33,24,33v-0.025c-5.668-0.182-9.289-2.066-10.975-4.975 c-3.665,0.042-6.856,0.405-8.677,0.707c-0.058-0.327-0.108-0.656-0.151-0.987c1.797-0.296,4.843-0.647,8.345-0.714 c-0.112-0.276-0.209-0.559-0.291-0.849c-3.511-0.178-6.541-0.039-8.187,0.097c-0.02-0.332-0.047-0.663-0.051-0.999 c1.649-0.135,4.597-0.27,8.018-0.111c-0.079-0.5-0.13-1.011-0.13-1.543c0-1.7,0.6-3.5,1.7-5c-0.5-1.7-1.2-5.3,0.2-6.6 c2.7,0,4.6,1.3,5.5,2.1C21,13.4,22.9,13,25,13s4,0.4,5.6,1.1c0.9-0.8,2.8-2.1,5.5-2.1c1.5,1.4,0.7,5,0.2,6.6c1.1,1.5,1.7,3.2,1.6,5 c0,0.484-0.045,0.951-0.11,1.409c3.499-0.172,6.527-0.034,8.204,0.102c-0.002,0.337-0.033,0.666-0.051,0.999 c-1.671-0.138-4.775-0.28-8.359-0.089c-0.089,0.336-0.197,0.663-0.325,0.98c3.546,0.046,6.665,0.389,8.548,0.689 c-0.043,0.332-0.093,0.661-0.151,0.987c-1.912-0.306-5.171-0.664-8.879-0.682C35.112,30.873,31.557,32.75,26,32.969V33 c2.6,0,5,3.9,5,6.6V45c0,0.823,0.498,1.53,1.209,1.836C41.37,43.804,48,35.164,48,25C48,12.318,37.683,2,25,2S2,12.318,2,25 C2,35.164,8.63,43.804,17.791,46.836z" /></svg>
                <span>Github</span>
              </a>
              <a href="#" className="custom-button py-2 px-4  rounded inline-flex gap-3  items-center">
                <svg className="w-8 " fill="#578cf4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" ><path d="M42,37c0,2.762-2.238,5-5,5H11c-2.761,0-5-2.238-5-5V11c0-2.762,2.239-5,5-5h26c2.762,0,5,2.238,5,5V37z" /><path fill="#FFF" d="M12 19H17V36H12zM14.485 17h-.028C12.965 17 12 15.888 12 14.499 12 13.08 12.995 12 14.514 12c1.521 0 2.458 1.08 2.486 2.499C17 15.887 16.035 17 14.485 17zM36 36h-5v-9.099c0-2.198-1.225-3.698-3.192-3.698-1.501 0-2.313 1.012-2.707 1.99C24.957 25.543 25 26.511 25 27v9h-5V19h5v2.616C25.721 20.5 26.85 19 29.738 19c3.578 0 6.261 2.25 6.261 7.274L36 36 36 36z" /></svg>
                <span>Linkedin</span>
              </a>

            </div>
          </div>

        </div>

        <div className="container-about-me container flex flex-wrap flex-col items-center justify-center p-10 w-screen h-screen mx-auto  ">
          <h3 className="mb-8 text-3xl dark:text-gray-200 "> Sobre mim  </h3>
          <div className="flex  md:flex-row md:max-w-7xl md:w-full justify-center">
            <img src="/profile.jpg" alt="profile" className="md:w-96 object-cover rounded-t-lg h-96  md:w-96 md:rounded-full" />
            <div className="flex flex-row flex-wrap justify-around items-center ">

              <ul className="flex flex-col flex-wrap  space-y-4 text-left md:max-w-96 text-gray-200 ">
                <li className="flex items-center space-x-3 rtl:space-x-reverse">
                  <svg className="flex-shrink-0 w-3.5 h-3.5 dark:text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M1 5.917 5.724 10.5 15 1.5" />
                  </svg>
                  <span>Individual configuration</span>
                </li>
                <li className="flex items-center space-x-3 rtl:space-x-reverse">
                  <svg className="flex-shrink-0 w-3.5 h-3.5 dark:text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M1 5.917 5.724 10.5 15 1.5" />
                  </svg>
                  <span>No setup, or hidden fees</span>
                </li>
                <li className="flex items-center space-x-3 rtl:space-x-reverse">
                  <svg className="flex-shrink-0 w-3.5 h-3.5 dark:text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M1 5.917 5.724 10.5 15 1.5" />
                  </svg>
                  <span>Team size: <span className="font-semibold dark:text-yellow-500">1 developer</span></span>
                </li>
                <li className="flex items-center space-x-3 rtl:space-x-reverse">
                  <svg className="flex-shrink-0 w-3.5 h-3.5 dark:text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M1 5.917 5.724 10.5 15 1.5" />
                  </svg>
                  <span>Premium support: <span className="font-semibold dark:text-yellow-500">6 months</span></span>
                </li>
                <li className="flex items-center space-x-3 rtl:space-x-reverse">
                  <svg className="flex-shrink-0 w-3.5 h-3.5 dark:text-yellow-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
                    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M1 5.917 5.724 10.5 15 1.5" />
                  </svg>
                  <span>Free updates: <span className="font-semibold dark:text-yellow-500">6 months</span></span>
                </li>
                <li className="flex items-center space-x-3 rtl:space-x-reverse">
                  <button className="custom-button py-2 px-4  rounded inline-flex gap-3  items-center" type="button"> Download CV </button>
                </li>
              </ul>
              <img src="/imageAboutMe.png" alt="profile" className="  object-scale-down w-1/3 h-auto" />


            </div>

          </div>


        </div>


        <div className="container flex flex-wrap flex-col items-center justify-center p-10 h-screen w-screen mx-auto">
          <h3 className="mb-8 text-3xl dark:text-gray-200"> Projetos  </h3>
          <div className="flex flex-wrap flex-column gap-8 mx-auto items-center justify-center ">
            <ProjectCard> </ProjectCard>
            <ProjectCard> </ProjectCard>
            <ProjectCard> </ProjectCard>
          </div>


        </div>

        <div className=" flex flex-wrap flex-col items-center justify-center  p-3  ">
          <h3 className="mb-8 text-3xl dark:text-gray-200"> Tecnologias  </h3>
          <div className="flex   flex-row   ">
            <TecCard type="1" title="BackEnd"> </TecCard>
            <TecCard type="2" title="FrontEnd" > </TecCard>
            <TecCard type="3" title="Infraestrutura" > </TecCard>
            <TecCard type="4" title="Banco de Dados" > </TecCard>



          </div>


        </div>


        <div className=" flex flex-wrap flex-col items-center justify-center p-3 mt-10  ">
          <p className="mb-8 text-xl dark:text-gray-200"> Copyright © 2024 by Pedro Santos. All rights reserved.  </p>



        </div>

      </body>
    </html >
  );
}
